export let data = [
  {
    img: "https://www.shutterstock.com/image-photo/portrait-smiling-young-college-student-260nw-1192615495.jpg",
    name: "Mohamed",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O+",
  },
  {
    img: "https://cdn.pixabay.com/photo/2018/06/27/07/45/college-student-3500990__340.jpg",
    name: "Arun",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18 ",
    bloodGroup: "A+",
  },
  {
    img: "https://www.shutterstock.com/image-photo/confident-handsome-student-holding-books-260nw-366568778.jpg",
    name: "Tamilselvan",
    batch: "B42 Tamil",
    gender: "Male",
    age: "17",
    bloodGroup: "B+",
  },
  {
    img: "https://media.istockphoto.com/photos/handsome-afro-student-posing-on-bookshelves-background-picture-id1171062918?b=1&k=20&m=1171062918&s=612x612&w=0&h=Kb6lK8UN5YonWr9X4idrzzbMyHU5bauiXSUDGm4wdcs=",
    name: "Jayavel",
    batch: "B42 Tamil",
    gender: "male",
    age: "16",
    bloodGroup: "AB+",
  },
  {
    img: "https://img.freepik.com/premium-photo/male-student-with-notebooks-backpack-pink-background_185193-75180.jpg?w=2000",
    name: "Sanjay",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://img.freepik.com/premium-photo/young-handsome-man-smiling-happily-waving-hand-welcoming-greeting-you-university-student-concept_1194-292210.jpg?w=360",
    name: "Ashok",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://cdn.pixabay.com/photo/2018/06/27/07/45/college-student-3500990__340.jpg",
    name: "Vijay",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://cdn.pixabay.com/photo/2018/06/27/07/45/college-student-3500990__340.jpg",
    name: "Murali",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://img.freepik.com/free-photo/education-courses-university-concept-surprised-happy-smiling-guy-seeing-something-amazed-while-heading-class-college-board-school-holding-backpack-with-notebooks_1258-60085.jpg?auto=format&h=200",
    name: "Srijai",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://www.shutterstock.com/image-photo/portrait-smiling-young-college-student-260nw-1192615495.jpg",
    name: "Hamesh",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://img.freepik.com/free-photo/education-courses-university-concept-surprised-happy-smiling-guy-seeing-something-amazed-while-heading-class-college-board-school-holding-backpack-with-notebooks_1258-60085.jpg?auto=format&h=200",
    name: "Kalai",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O-",
  },
  {
    img: "https://www.shutterstock.com/image-photo/portrait-smiling-young-college-student-260nw-1192615495.jpg",
    name: "Ajith",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18",
    bloodGroup: "O+",
  },
  {
    img: "https://cdn.pixabay.com/photo/2018/06/27/07/45/college-student-3500990__340.jpg",
    name: "Tanish",
    batch: "B42 Tamil",
    gender: "Male",
    age: "18 ",
    bloodGroup: "A+",
  },
  {
    img: "https://www.shutterstock.com/image-photo/confident-handsome-student-holding-books-260nw-366568778.jpg",
    name: "Venish",
    batch: "B42 Tamil",
    gender: "Male",
    age: "17",
    bloodGroup: "B+",
  },
];
